[pkg] don't autostart the agent

diff --git a/packaging/debian/dd-trace-agent.postinst b/packaging/debian/dd-trace-agent.postinst
--- a/packaging/debian/dd-trace-agent.postinst
+++ b/packaging/debian/dd-trace-agent.postinst
@@ -5,10 +5,10 @@ set -e
 case "$1" in
     configure)
         echo "Registering service dd-trace-agent"
-        if which initctl > /dev/null 2>&1; then
+        if command -v initctl > /dev/null 2>&1; then
             # use upstart if available
             initctl reload-configuration
-        elif which update-rc.d >/dev/null 2>&1; then
+        elif command -v update-rc.d >/dev/null 2>&1; then
             # use sysvinit
             update-rc.d dd-trace-agent defaults
             update-rc.d dd-trace-agent enable >/dev/null 2>&1
@@ -16,18 +16,18 @@ case "$1" in
             # TODO: fix bogus exit code
             exit 123
         fi
-
-        echo "Starting service dd-trace-agent"
-        if which start > /dev/null 2>&1; then
-            stop dd-trace-agent || true
-            start dd-trace-agent
-        elif which invoke-rc.d >/dev/null 2>&1; then
-            invoke-rc.d dd-trace-agent stop || true
-            invoke-rc.d dd-trace-agent start
-        else
-            # TODO: fix bogus exit code
-            exit 123
-        fi
+        #
+        # echo "Starting service dd-trace-agent"
+        # if command -v start > /dev/null 2>&1; then
+        #     stop dd-trace-agent || true
+        #     start dd-trace-agent
+        # elif command -v invoke-rc.d >/dev/null 2>&1; then
+        #     invoke-rc.d dd-trace-agent stop || true
+        #     invoke-rc.d dd-trace-agent start
+        # else
+        #     # TODO: fix bogus exit code
+        #     exit 123
+        # fi
         ;;
 esac
 
