config: use shared config utility from datadog-agent (#526)

diff --git a/vendor/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent/posttrans b/vendor/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent/posttrans
--- a/vendor/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent/posttrans
+++ b/vendor/github.com/DataDog/datadog-agent/omnibus/package-scripts/agent/posttrans
@@ -16,13 +16,12 @@ ln -sf $INSTALL_DIR/bin/agent/agent /usr/bin/datadog-agent
 
 echo "Enabling service $SERVICE_NAME"
 if command -v systemctl >/dev/null 2>&1; then
-    systemctl enable $SERVICE_NAME
+    systemctl enable $SERVICE_NAME || echo "[ WARNING ]\tCannot enable $SERVICE_NAME with systemctl"
 elif command -v initctl >/dev/null 2>&1; then
     # start/stop policy is already defined in the upstart job file
     :
 else
-    echo "[ ${Red}FAILED ${RCol}]\tUnsupported init system."
-    exit 1
+    echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agent package only provides service files for systemd and upstart."
 fi
 
 # TODO: Use a configcheck command on the agent to determine if it's safe to restart,
@@ -34,8 +33,7 @@ if [ -f "$CONFIG_DIR/datadog.yaml" ]; then
     elif command -v initctl >/dev/null 2>&1; then
         initctl start $SERVICE_NAME || initctl restart $SERVICE_NAME || true
     else
-        echo "[ ${Red}FAILED ${RCol}]\tUnsupported init system."
-        exit 1
+        echo "[ WARNING ]\tCannot detect a supported init system. The datadog-agent package only provides service files for systemd and upstart."
     fi
 else
     # No datadog.yaml file is present. This is probably a clean install made with the
